In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
path = "../../All_data_sets/model_data_set/random_forest/cardekho_imputated.csv"

In [3]:
df = pd.read_csv( path )

df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.shape

(15411, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [6]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='object')

In [7]:
delete_columns = ['Unnamed: 0', 'car_name', 'brand']

### delete the unwanted columns

In [9]:
df.drop(columns=delete_columns , inplace=True)

In [10]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

### get categorical and numerical columns and descrete and continuous features

In [13]:
cat_cols = [ feature for feature in df.columns if df[feature].dtype == 'O' ]
num_cols = [ feature for feature in df.columns if df[feature].dtype != 'O' ]

In [15]:
descrete_cols = [ feature for feature in num_cols if len( df[feature].unique() ) <= 25 ]
continuous_cols = [ feature for feature in num_cols if len( df[feature].unique() ) > 25 ]

### check the unique values of each categorical feature

In [19]:
for feature in cat_cols:
    print(feature)
    print( df[feature].unique() )

model
['Alto' 'Grand' 'i20' 'Ecosport' 'Wagon R' 'i10' 'Venue' 'Swift' 'Verna'
 'Duster' 'Cooper' 'Ciaz' 'C-Class' 'Innova' 'Baleno' 'Swift Dzire'
 'Vento' 'Creta' 'City' 'Bolero' 'Fortuner' 'KWID' 'Amaze' 'Santro'
 'XUV500' 'KUV100' 'Ignis' 'RediGO' 'Scorpio' 'Marazzo' 'Aspire' 'Figo'
 'Vitara' 'Tiago' 'Polo' 'Seltos' 'Celerio' 'GO' '5' 'CR-V' 'Endeavour'
 'KUV' 'Jazz' '3' 'A4' 'Tigor' 'Ertiga' 'Safari' 'Thar' 'Hexa' 'Rover'
 'Eeco' 'A6' 'E-Class' 'Q7' 'Z4' '6' 'XF' 'X5' 'Hector' 'Civic' 'D-Max'
 'Cayenne' 'X1' 'Rapid' 'Freestyle' 'Superb' 'Nexon' 'XUV300' 'Dzire VXI'
 'S90' 'WR-V' 'XL6' 'Triber' 'ES' 'Wrangler' 'Camry' 'Elantra' 'Yaris'
 'GL-Class' '7' 'S-Presso' 'Dzire LXI' 'Aura' 'XC' 'Ghibli' 'Continental'
 'CR' 'Kicks' 'S-Class' 'Tucson' 'Harrier' 'X3' 'Octavia' 'Compass' 'CLS'
 'redi-GO' 'Glanza' 'Macan' 'X4' 'Dzire ZXI' 'XC90' 'F-PACE' 'A8' 'MUX'
 'GTC4Lusso' 'GLS' 'X-Trail' 'XE' 'XC60' 'Panamera' 'Alturas' 'Altroz'
 'NX' 'Carnival' 'C' 'RX' 'Ghost' 'Quattroporte' 'Gurkha']
seller_type
['Individual' 'Dealer' 'Trustmark Dealer']
fuel_type
['Petrol' 'Diesel' 'CNG' 'LPG' 'Electric']
transmission_type
['Manual' 'Automatic']

### use label encoding for model and one hot encoding for seller_type fuel_type transmission_type

### Encoding the categorical features and standardingbthe numerical columns

In [20]:
from sklearn.preprocessing import OneHotEncoder , LabelEncoder ,StandardScaler

In [48]:
ohe = OneHotEncoder( drop='first' , dtype=int )
le = LabelEncoder()
scaler = StandardScaler()

In [35]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [36]:
df['model'] = le.fit_transform( df['model']  )

In [37]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [38]:
num_features = num_cols[:-1]
num_features

['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']

In [41]:
cat_features = cat_cols[1:]
cat_features

['seller_type', 'fuel_type', 'transmission_type']

In [39]:
from sklearn.compose import ColumnTransformer

In [42]:
preprocessor = ColumnTransformer(
    transformers=[
        ("OneHotEncoder",ohe,cat_features),
        ("StandardScaler",scaler,num_features)
    ],
    remainder='passthrough'
)

### seperate the independent and dependent columns

In [45]:
X = df.iloc[:,:-1]
y = df.iloc[ : ,-1 ]

In [51]:
X

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
15406,117,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
15407,42,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
15408,77,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
15409,114,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
15410,25,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [55]:
X_trasformed = preprocessor.fit_transform(X)
pd.DataFrame(X_trasformed)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022,7.0
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022,54.0
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022,118.0
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022,7.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022,117.0
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444,42.0
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022,77.0
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444,114.0
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022,25.0

In [53]:
X_trasformed.shape

(15411, 14)

In [54]:
X.shape

(15411, 10)

### train test split

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
X_train , X_test , y_train , y_test = train_test_split( X_trasformed,y , test_size=0.25, random_state=43 )

In [59]:
from sklearn.ensemble import RandomForestRegressor

In [60]:
rfr = RandomForestRegressor()

In [61]:
rfr.fit( X_train , y_train )

RandomForestRegressor()

In [62]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [63]:
def evaluation_metrics( y_true , y_prediction ):
    r2 = r2_score( y_true , y_prediction )
    mse = mean_squared_error( y_true , y_prediction )
    mae = mean_absolute_error( y_true , y_prediction )
    
    print(f'R2 score: {r2}')
    print(f'Mean squared error: {mse}')
    print(f'Mean Absolute error:{mae}')
    
    return r2,mse,mae

In [64]:
y_pred = rfr.predict( X_test )

In [65]:
evaluation_metrics( y_test,y_pred )

R2 score: 0.9074251386774855
Mean squared error: 82102957280.02928
Mean Absolute error:100383.2901847266

(0.9074251386774855, 82102957280.02928, 100383.2901847266)