In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
path = '../../All_data_sets/model_data_set/random_forest/Travel.csv'

In [3]:
df = pd.read_csv(path)

df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [4]:
df.shape

(4888, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [6]:
df.rename(columns=str.lower,inplace=True)

In [7]:
columns = df.columns

In [8]:
columns

Index(['customerid', 'prodtaken', 'age', 'typeofcontact', 'citytier',
       'durationofpitch', 'occupation', 'gender', 'numberofpersonvisiting',
       'numberoffollowups', 'productpitched', 'preferredpropertystar',
       'maritalstatus', 'numberoftrips', 'passport', 'pitchsatisfactionscore',
       'owncar', 'numberofchildrenvisiting', 'designation', 'monthlyincome'],
      dtype='object')

In [9]:
df['gender'].value_counts()

gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [10]:
df['gender'] = df['gender'].replace(to_replace='Fe Male' ,value='Female' )

In [11]:
df['maritalstatus'].value_counts()

maritalstatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

### combine the single and unmarried

In [12]:
df['maritalstatus'] = df['maritalstatus'].replace(to_replace='Unmarried' ,value='Single' )

In [13]:
df['maritalstatus'].value_counts()

maritalstatus
Married     2340
Single      1598
Divorced     950
Name: count, dtype: int64

### Checking the null values

In [14]:
# columns with null values

features_with_na = [feature for feature in columns if df[feature].isnull().sum()>=1 ]

features_with_na

['age',
 'typeofcontact',
 'durationofpitch',
 'numberoffollowups',
 'preferredpropertystar',
 'numberoftrips',
 'numberofchildrenvisiting',
 'monthlyincome']

In [15]:
for feature in features_with_na:
    print(f'{feature} : { np.round( df[feature].isnull().mean()*100 , 3 ) } % missing values!' )

age : 4.624 % missing values!
typeofcontact : 0.511 % missing values!
durationofpitch : 5.135 % missing values!
numberoffollowups : 0.921 % missing values!
preferredpropertystar : 0.532 % missing values!
numberoftrips : 2.864 % missing values!
numberofchildrenvisiting : 1.35 % missing values!
monthlyincome : 4.767 % missing values!

In [16]:
df.head(2)

,customerid,prodtaken,age,typeofcontact,citytier,durationofpitch,occupation,gender,numberofpersonvisiting,numberoffollowups,productpitched,preferredpropertystar,maritalstatus,numberoftrips,passport,pitchsatisfactionscore,owncar,numberofchildrenvisiting,designation,monthlyincome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0

In [17]:
df[features_with_na].select_dtypes( exclude='object' ).describe()

,age,durationofpitch,numberoffollowups,preferredpropertystar,numberoftrips,numberofchildrenvisiting,monthlyincome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

### Fill the nan values

In [18]:
df['age'] = df['age'].fillna( df['age'].median() )
df['typeofcontact'] = df['typeofcontact'].fillna( df['typeofcontact'].mode()[0] )

In [19]:
df['durationofpitch'] = df['durationofpitch'].fillna( df['durationofpitch'].median() )

df['numberoffollowups'] = df['numberoffollowups'].fillna( df['numberoffollowups'].mode()[0] )

In [20]:
df['preferredpropertystar'] = df['preferredpropertystar'].fillna( df['preferredpropertystar'].mode()[0] )

df['numberoftrips'] = df['numberoftrips'].fillna( 0 )

In [21]:
df['numberofchildrenvisiting'] = df['numberofchildrenvisiting'].fillna( df['numberofchildrenvisiting'].mode()[0] )

df['monthlyincome'] = df['monthlyincome'].fillna( df['monthlyincome'].median() )

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customerid                4888 non-null   int64
 1   prodtaken                 4888 non-null   int64
 2   age                       4888 non-null   float64
 3   typeofcontact             4888 non-null   object
 4   citytier                  4888 non-null   int64
 5   durationofpitch           4888 non-null   float64
 6   occupation                4888 non-null   object
 7   gender                    4888 non-null   object
 8   numberofpersonvisiting    4888 non-null   int64
 9   numberoffollowups         4888 non-null   float64
 10  productpitched            4888 non-null   object
 11  preferredpropertystar     4888 non-null   float64
 12  maritalstatus             4888 non-null   object
 13  numberoftrips             4888 non-null   float64
 14  passport                  4888 non-null   int64
 15  pitchsatisfactionscore    4888 non-null   int64
 16  owncar                    4888 non-null   int64
 17  numberofchildrenvisiting  4888 non-null   float64
 18  designation               4888 non-null   object
 19  monthlyincome             4888 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

### Feature extraction

In [23]:
#create the new column with the visiting peaple

df['total_visiting'] = df['numberofpersonvisiting']+df['numberofchildrenvisiting']

In [24]:

delete_col = ['customerid', 'numberofpersonvisiting','numberofchildrenvisiting' ]

In [25]:
df.drop(columns=delete_col , inplace=True)

In [26]:
#numerical and categorical featutres

num_cols = [ feature for feature in df.columns if df[feature].dtype != 'O' ]

cat_cols = [ feature for feature in df.columns if df[feature].dtype == 'O' ]

print(f'Numerical columns:{num_cols}')

print('-------------------------------------------------------------------------------------------------------------------------------------------')
print(f'Categorical columns:{cat_cols}')

Numerical columns:['prodtaken', 'age', 'citytier', 'durationofpitch', 'numberoffollowups', 'preferredpropertystar', 'numberoftrips', 'passport', 'pitchsatisfactionscore', 'owncar', 'monthlyincome', 'total_visiting']
-------------------------------------------------------------------------------------------------------------------------------------------
Categorical columns:['typeofcontact', 'occupation', 'gender', 'productpitched', 'maritalstatus', 'designation']

In [27]:
# Descrite features

descrite_features = [ feature for feature in df.columns if len( df[feature].unique() ) <= 25]

descrite_features

['prodtaken',
 'typeofcontact',
 'citytier',
 'occupation',
 'gender',
 'numberoffollowups',
 'productpitched',
 'preferredpropertystar',
 'maritalstatus',
 'numberoftrips',
 'passport',
 'pitchsatisfactionscore',
 'owncar',
 'designation',
 'total_visiting']

In [28]:
# Continuous features


continuous_features = [ feature for feature in df.columns if len( df[feature].unique() ) > 25]

continuous_features

['age', 'durationofpitch', 'monthlyincome']

In [29]:
df.head()

,prodtaken,age,typeofcontact,citytier,durationofpitch,occupation,gender,numberoffollowups,productpitched,preferredpropertystar,maritalstatus,numberoftrips,passport,pitchsatisfactionscore,owncar,designation,monthlyincome,total_visiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X = df.drop( columns='prodtaken' , axis=1  )

y = df['prodtaken']

In [32]:
X_train , X_test , y_train , y_test = train_test_split( X , y , test_size=0.25 , random_state=42 )

In [33]:
X_train.shape , X_test.shape

((3666, 17), (1222, 17))

### transform the data

In [34]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler

from sklearn.compose import ColumnTransformer

In [35]:
scaler = StandardScaler()

encoder = OneHotEncoder( drop='first' )

In [36]:
cat_cols = X.select_dtypes(include='object').columns

num_cols = X.select_dtypes(exclude='object').columns

In [37]:
preprocessor = ColumnTransformer(
    [
        ( 'OneHotEncoder' , encoder, cat_cols  ),
        ( 'StandardScaler' , scaler, num_cols )
    ]
)

In [38]:
X_train_processed = preprocessor.fit_transform( X_train )

In [39]:
X_test_processed = preprocessor.transform( X_test )

### Model

In [40]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score , classification_report , confusion_matrix

In [41]:
rfc = RandomForestClassifier()

In [42]:
rfc.fit( X_train_processed , y_train )

RandomForestClassifier()

In [43]:
y_pred = rfc.predict( X_test_processed )

In [44]:

print('Confusion matrix')
print(confusion_matrix(y_test , y_pred ))

print(f'Accuracy score is:{accuracy_score(y_test , y_pred)}')

print('Classification Report')
print(classification_report(y_test , y_pred ))

SyntaxError: incomplete input (270175870.py, line 7)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
# test on different models

models = {
    "Logistic regression":LogisticRegression(),
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestClassifier(),
}

In [ ]:
for i in range( len( list(models) ) ):
    model = list(models.values())[i]
    model.fit( X_train_processed , y_train )
    
    y_train_pred = model.predict(  X_train_processed )
    
    y_test_pred = model.predict(  X_test_processed )

    

    print(f'Prediction for the model {list(models)[i]}')
    
    # Training Prediction
    print('Training Predictions')
    print('Confusion matrix')
    print(confusion_matrix(y_train , y_train_pred ))
    print(f'Accuracy score is:{accuracy_score(y_train , y_train_pred)}')
    print('Classification Report')
    print( classification_report(y_train , y_train_pred )  )

    print('----------------------------------------------------------------------------------------------------------------------------------------------------')
          
    # Testing Prediction
    print('Training Predictions')
    print('Confusion matrix')
    print(confusion_matrix(y_test , y_test_pred ))
    print(f'Accuracy score is:{accuracy_score(y_test , y_test_pred)}')
    print('Classification Report')
    print(classification_report(y_test , y_test_pred ))
          
    print("===================================================================================================================================================================")